Add support for Ubuntu 16.04 and systemd
kbrebanov/ansible-vault pull request #14
Opened 2016-10-21 09:34 UTC by MiLk

I've added the systemd service file to make Vault work with systemd on Ubuntu 16.04.

I've also replaced the command module by unarchive to unzip the zipfile with the vault binary.

2016-10-24 05:21 UTC, MiLk commented
@kbrebanov I've updated my PR to use your latest changes.
But I think all the `become: yes` should be removed and moved to the playbook level.

Do you want me to do other changes before merging this PR?

2016-10-24 13:52 UTC, kbrebanov commented on tasks/main.yml
> +- name: Detect if systemd is present
This task can be removed and check if the distribution release is xenial instead.

2016-10-24 13:53 UTC, kbrebanov commented on tasks/main.yml
> +  when: vault_systemctl_stat.stat.exists is defined and vault_systemctl_stat.stat.exists == True
Just check if it's xenial:

ansible_distribution_release|lower == 'xenial'

2016-10-24 13:53 UTC, kbrebanov commented on tasks/main.yml
> +  when: vault_systemctl_stat.stat.exists is not defined or vault_systemctl_stat.stat.exists == False
check if it's Trusty:

ansible_distribution_release|lower == 'trusty'

2016-10-24 13:54 UTC, kbrebanov commented on templates/vault.service.j2
> +StandardOutput=journal
Would it be possible to send the logs to /var/log/vault.log like the Upstart script does? To have some consistency.

2016-10-24 13:57 UTC, kbrebanov requested changes
It would be great if this would be split into 2 different commits.

One for the unarchive module and one for adding support for Xenial.

You should also uncomment the environment section for Xenial in the Travis configuration file so that the tests will be executed on a Xenial instance.

As for the become directives. I disagree with simply using it at the playbook level. To me, that is the same bad practice as logging in as root when you don't need to. Only tasks that need elevated privileges should do so.

2016-10-25 02:19 UTC, MiLk commented
I didn't use `ansible_distribution_release` to avoid relying on fact, but you already use `ansible_distribution`,  so it's ok.

I've configured the systemd service file to send the logs to a file instead of the journal, but it's still possible to override the `vault_log_file` with `journal` to send the logs to `journald` which is consistent across all the services running on a system using systemd.

2016-10-25 21:56 UTC, kbrebanov commented
Could you just use a default variable named 'use_systemd_journal' and set it to 'false' by default?
Then all you would need is a conditional in the template.

You could probably also get rid of the following tasks:
 
- Check if the log file is present
- Create vault log file

Don't forget to also update **defaults/main.yml** and **README.md** accordingly.

2016-10-26 00:47 UTC, MiLk commented
The consul user can not write a new file into the `/var/log` folder, that's why I had to add these two tasks. If not the service does not start.

2016-10-26 13:35 UTC, kbrebanov commented
I'm sorry. I don't understand what the **consul** user has to do with this role.
Are you applying this role on your machine using the **consul** user?

This role only has a dependency on *unzip*. Consul is not required to apply this role.
Also, the Travis CI tests will execute as root so it should have no issues creating the log file.

2016-10-27 00:50 UTC, MiLk commented
Right, `vault` user, not `consul`.

The [command executed](https://github.com/MiLk/ansible-vault/blob/systemd/templates/vault.service.j2#L10) by systemd will be run with the [`vault` user](https://github.com/MiLk/ansible-vault/blob/systemd/templates/vault.service.j2#L14-L15).
The [`vault_log_file`](https://github.com/MiLk/ansible-vault/blob/systemd/vars/main.yml#L9) being in `/var/log` and the `vault` user not being able to write in this directory, the command fails.

2016-10-27 15:41 UTC, kbrebanov commented
Ok. Since it's best practice to log to the journal with systemd, let's just log to it.
You can remove everything that relates to logging somewhere else than the journal and the task that creates the log file.

2016-10-28 03:32 UTC, MiLk commented
I've removed the 2 commits related to the log file.

2016-10-28 12:59 UTC, kbrebanov approved these changes

2016-10-28 13:00 UTC, merged